#!/usr/bin/env bash

typeset MYSELF="$(realpath $0)"
typeset MYPATH="${MYSELF%/*}"

# Load main library
typeset -a ammpaths=("$MYPATH/ammlib" "$HOME/.ammlib" "/etc/ammlib")
for ammpath in "${ammpaths[@]}" fail; do
	[[ -e "$ammpath/ammlib" ]] && source "$ammpath/ammlib" && break
done
if [[ "$ammpath" == "fail" ]]; then
	echo >&2 "Unable to find ammlib in paths '${ammpaths[@]}'"
	echo >&2 "Download it with 'git clone https://github.com/Saruspete/ammlib.git $MYPATH'"
	exit 1
fi

# From https://bytesbin.com/how-to-download-a-large-file-from-google-drive-quickly/

# Load the required libraries
ammLib::Require "optparse" "http"

TMPDIR="$(ammLib::TmpPathGet)"


for fileid in "$@"; do

	# Filter-out url if any
	fileid="${fileid#*/file/d/}"
	fileid="${fileid%%/*}"

	typeset cookiejar="$TMPDIR/$fileid.cookiejar"

	typeset metadata="$(ammHttp::Get "https://drive.google.com/uc?export=download&id=$fileid" "follow cookiejar=$cookiejar")"

	# Act only on size, as it can be very large
	typeset metadata2="${metadata//uc-download-link/}"
	if [[ "${#metadata}" == "${#metadata2}" ]]; then
		ammLog::Warning "Cannot find object with ID '$fileid'. Are its sharing settings set as 'anyone with the link?'"
		continue
	fi

	# Extract the url to confirm large files
	#typeset confirm="${metadata#*uc-download-link*href=\"/}"
	#confirm="${confirm%%\">*}"
	#confirm="${confirm//\&amp;/\&}"
	#ammLog::Debug "Extracted confirmation URL as '$confirm'"


	# Extract the filename
	typeset filename="${metadata#*open?id=*>}"
	typeset filesize="$filename"
	filename="${filename%%</a>*}"
	filesize="${filesize#*</a> (}"
	filesize="${filesize%%)*}"

	ammLog::Info "Downloading: $filename ($filesize)"

	# Fetch the file, using the jar in readonly
	#ammHttp::Fetch "https://drive.google.com/${confirm}" "$filename" "follow cookieload=$cookiejar"
	ammHttp::Fetch "https://drive.google.com/uc?export=download&id=$fileid&confirm=t" "$filename" "follow cookieload=$cookiejar"

done
